### PR TITLE
Make it possible to publish to https://pypi.org/

### LINKED ISSUE #7: Publish beancount-ethereum-importer to make using it easier
I want to be able to use the beancount-ethereum-importer, to do so I want to be able to depend on it in a simple way.

To do so I suggest publishing it to https://pypi.org/ from github actions when a github release is created.

### PR DESCRIPTION
**Pull request by owodunni**
In order for `beancount_ethereum` to be easily reused in beancount
projects it should be published as a pip package.

I have tried to add necessary information to make this possible as well
as a github action which will be triggered when a github release is
created.

Closes #7

### CODE REVIEW

**Comment by xuhcc** [comment]
Thanks @owodunni !
I would like to publish the package manually, whithout using GitHub actions. Any recommendations?
I've checked the PyPI HowTo (https://packaging.python.org/en/latest/flow/) and it suggests using `pyproject.toml` file. Is it really necessary or `setup.py` will be enough?

**Comment by owodunni** [comment]
Your welcome! Its a nice project and I'm happy to contribute.

We should be fine with just a `setup.py`, thats all I have in my other project https://github.com/owodunni/GageRnR. Uploading is simple using twine, it is what they suggest in the PyPI HowTo as well.

From command line you will do:

```
pip install build twine
python -m build --sdist --wheel --outdir dist/
twine upload dist/*
```

Twine will then ask you to authenticate.

Out of curiosity, why don't you want to upload with a github action?

Do you want me to remove the action?

**Comment by xuhcc** [comment]
I don't want to depend on Github, I think eventually I'll move the repo to some other platform.
So yes, let's remove the action.
I've tried to build the package, so far everything seems to be working.

**Comment by owodunni** [comment]
Fair enough. I added a Makefile with the necessary deployment script. You should be able to build and deploy by doing:

```
make deploy
```

**Pull request merged**
